/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        display: ['Space Grotesk', 'sans-serif'],
        body:    ['Inter', 'sans-serif'],
        mono:    ['JetBrains Mono', 'monospace'],
      },
      colors: {
        base:     '#07090F',
        surface:  '#0D1117',
        elevated: '#131A27',
        primary:  '#6366F1',
        cyan:     '#22D3EE',
        clay:     '#C084FC',
        amber:    '#FB923C',
        success:  '#22C55E',
      },
      backgroundImage: {
        'grad-primary': 'linear-gradient(135deg, #6366F1, #22D3EE)',
        'grad-full':    'linear-gradient(135deg, #6366F1, #22D3EE, #C084FC)',
      },
      animation: {
        'float':      'float 8s ease-in-out infinite',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
        'truck':      'truckDrive 5.5s linear infinite',
        'road':       'roadScroll 0.55s linear infinite',
        'bar':        'barRise var(--bd) ease-in-out infinite var(--bdel)',
        'money':      'moneyFloat var(--md) ease-out infinite var(--mdel)',
        'heart':      'heartUp var(--hd) ease-out infinite var(--hdel)',
        'gear-r':     'gearR 9s linear infinite',
        'gear-l':     'gearL 4.5s linear infinite',
        'conveyor':   'conveyorMove 0.38s linear infinite',
        'bottle':     'bottleTravel 4s linear infinite',
        'smoke':      'smokeRise 2.2s ease-out infinite var(--sd)',
        'puff':       'exhaustPuff 1.1s ease-out infinite',
        'twinkle':    'twinkle var(--td) ease-in-out infinite',
        'notif':      'notifPop var(--nd) ease-out infinite var(--ndel)',
        'screen':     'screenPulse 2.5s ease-in-out infinite',
        'reveal':     'revealUp 0.6s ease forwards',
        'fade-in':    'fadeIn 0.5s ease forwards',
        'counter':    'counterUp 1s ease-out forwards',
      },
      keyframes: {
        float:         { '0%,100%': { transform: 'translate(0,0) scale(1)' }, '50%': { transform: 'translate(8px,-12px) scale(1.05)' } },
        pulseSoft:     { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.4' } },
        truckDrive:    { '0%': { transform: 'translateX(-250px)' }, '100%': { transform: 'translateX(1200px)' } },
        roadScroll:    { '0%': { transform: 'translateX(0)' }, '100%': { transform: 'translateX(-50%)' } },
        barRise:       { '0%,100%': { height: 'var(--bmin)' }, '50%': { height: 'var(--bmax)' } },
        moneyFloat:    { '0%': { opacity: '0', transform: 'translateY(0) scale(.7)' }, '20%': { opacity: '.85' }, '100%': { opacity: '0', transform: 'translateY(-85px) scale(1)' } },
        heartUp:       { '0%': { opacity: '0', transform: 'translateY(0) scale(.4) rotate(var(--hr))' }, '18%': { opacity: '.95', transform: 'translateY(-12px) scale(1.1) rotate(var(--hr))' }, '100%': { opacity: '0', transform: 'translateY(-95px) scale(.7) rotate(var(--hr))' } },
        gearR:         { from: { transform: 'rotate(0deg)' }, to: { transform: 'rotate(360deg)' } },
        gearL:         { from: { transform: 'rotate(0deg)' }, to: { transform: 'rotate(-360deg)' } },
        conveyorMove:  { '0%': { transform: 'translateX(0)' }, '100%': { transform: 'translateX(-40px)' } },
        bottleTravel:  { '0%': { transform: 'translateX(380px)' }, '100%': { transform: 'translateX(-70px)' } },
        smokeRise:     { '0%': { opacity: '.45', transform: 'translate(0,0) scale(.5)' }, '100%': { opacity: '0', transform: 'translate(-4px,-40px) scale(1.8)' } },
        exhaustPuff:   { '0%': { opacity: '.55', transform: 'scale(.4) translate(0,0)' }, '100%': { opacity: '0', transform: 'scale(1.8) translate(-18px,-18px)' } },
        twinkle:       { '0%,100%': { opacity: '.15' }, '50%': { opacity: '.85' } },
        notifPop:      { '0%': { opacity: '0', transform: 'scale(.4) translateY(5px)' }, '25%': { opacity: '.75', transform: 'scale(1) translateY(0)' }, '100%': { opacity: '0', transform: 'scale(.9) translateY(-18px)' } },
        screenPulse:   { '0%,100%': { background: 'rgba(192,132,252,.05)' }, '50%': { background: 'rgba(192,132,252,.14)' } },
        revealUp:      { '0%': { opacity: '0', transform: 'translateY(30px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        fadeIn:        { from: { opacity: '0' }, to: { opacity: '1' } },
      },
      boxShadow: {
        glass:   '0 8px 32px rgba(0,0,0,0.3)',
        clay:    '6px 6px 12px rgba(99,102,241,0.25), -4px -4px 10px rgba(0,0,0,0.5)',
        primary: '0 8px 25px rgba(99,102,241,0.35)',
        glow:    '0 0 40px rgba(99,102,241,0.15)',
      },
    },
  },
  plugins: [],
}
